---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by f.guilleminot.
--- DateTime: 31/12/2020 09:32
---

local V, C = select(2, ...):unpack()

local Themes = V.Themes
local Profiles = V.Profiles

local function registers(module, submodule, object, table)
    for _, item in ipairs(table) do
        Profiles:RegisterOption(module, submodule, object, unpack(item))
    end
end

local function absorbOption(layout, module, submodule)

    local enable = true

    if layout == 'Compact' then
        enable = false
    end

    local data = {
        { nil, 'Enable', enable },
        { 'SlantingSettings', 'Enable', true },
        { 'SlantingSettings', 'IgnoreBackground', true },
        { 'SlantingSettings', 'FillInverse', true },
        { 'SlantingSettings', 'StaticLayer', 'BACKGROUND' },
        --RENDERING
        { 'Rendering', nil, 'VorkuiBubbles', 'ARTWORK' },
        { 'Rendering', nil, { 0, 0, 0, 1 }, 'BACKGROUND', 1 },
        --TAGS
        { 'Value', 'Layer', 'OVERLAY' },
        { 'Value', 'Font', 'ValueFont' },
        { 'Value', 'Point', "TOPLEFT", 'Health', "TOP" },
        { 'Value', 'Tag', '[Vorkui:HealthColor][Vorkui:Absorb]' },

    }

    --if layout == 'Expanded' then
    --elseif layout == 'Minimalist' then
    --elseif layout == 'Compact' then
    --  print ('|cFFFF1010 BAD PARTY LAYOUT |r')
    --end

    local size = #data

    if layout == 'Expanded' then
        data[size + 1] = { nil, 'Size', 114, 6 }
        data[size + 2] = { nil, 'Point', 'TOPRIGHT', 'Frame', 'TOPRIGHT', 0, -16 }
    elseif layout == 'Minimalist' then
        data[size + 1] = { nil, 'Size', 116, 6 }
        data[size + 2] = { nil, 'Point', 'TOPRIGHT', 'Frame', 'TOPRIGHT', 0, -10 }
    end

    registers(module, submodule, 'Absorb', data)

end

local function healthOption(layout, module, submodule)
    local data = {
        --TRANSFORM
        { nil, 'Enable', enable },
        ----SLANT
        { 'SlantingSettings', 'Enable', true },
        { 'SlantingSettings', 'IgnoreBackground', true },
        { 'SlantingSettings', 'StaticLayer', 'BACKGROUND' },
        --RENDERING
        { 'Rendering', nil, 'VorkuiDefault', 'ARTWORK' },
        { 'Rendering', nil, 'VorkuiBackground', 'BACKGROUND', 1 },
        { 'Rendering', nil, 'VorkuiBorder', 'OVERLAY' },
        --TAGS
        { 'Value', 'Layer', 'OVERLAY' },
        { 'Value', 'Font', 'ValueFont' },
        { 'Value', 'Tag', '[Vorkui:HealthColor(false)][Vorkui:Deficit:Curhp]' },

        { 'Percent', 'Layer', 'OVERLAY' },
        { 'Percent', 'Font', 'BigValueFont' },
        { 'Percent', 'Point', 'BOTTOMRIGHT', 'Frame', 'BOTTOMRIGHT' },
        { 'Percent', 'Tag', '[Vorkui:HealthColor(true)][Vorkui:PerHP]' },
    }

    local size = #data

    if layout == 'Expanded' then
        data[size + 1] = { nil, 'Size', 128, 24 }
        data[size + 2] = { nil, 'Point', 'TOPRIGHT', 'Absorb', 'BOTTOMRIGHT', -8, 0 }
        data[size + 3] = { 'Value', 'Point', 'TOPRIGHT', 'Health', 'TOP' }
    elseif layout == 'Minimalist' then
        data[size + 1] = { nil, 'Size', 126, 16 }
        data[size + 2] = { nil, 'Point', 'TOPRIGHT', 'Absorb', 'TOPRIGHT', -4, 0 }
        data[size + 3] = { 'Value', 'Point', 'TOPRIGHT', 'Health', 'TOP' }
    elseif layout == 'Compact' then
        data[size + 1] = { nil, 'Size', 156, 24 }
        data[size + 2] = { nil, 'Point', 'TOPRIGHT', 'Absorb', 'TOPRIGHT', 0, 0 }
        data[size + 3] = { 'Value', 'Point', 'CENTER', 'Health', 'CENTER' }
    else
        print ('|cFFFF1010 BAD PARTY LAYOUT |r')
    end

    registers(module, submodule, 'Health', data)

end

local function healthPredictionOption(layout, module, submodule)
    local data = {
        ----SLANT
        { nil, 'Enable', enable },
        { 'SlantingSettings', 'Enable', true },
        { 'SlantingSettings', 'IgnoreBackground', true },
        --RENDERING
        { 'Rendering', nil, 'VorkuiDefault', 'ARTWORK', 1 },
        { 'Rendering', nil, 'VorkuiBorder', 'OVERLAY' },
    }

    registers(module, submodule, 'HealthPrediction', data)

end

local function castbarOption(layout, module, submodule)

    local enable = true

    if layout == 'Compact' then
        enable = false
    end

    local data = {
        { nil, 'Enable', enable },
        --TRANSFORM
        { nil, 'Point', 'TOP', 'Frame', 'BOTTOM', 0, -2 },
        { nil, 'StatusBarColor', { 0, 0.5, 1, 1 } },
        --RENDERING
        { 'Rendering', nil, 'VorkuiDefault', 'ARTWORK' },
        { 'Rendering', nil, 'VorkuiBackground', 'BACKGROUND', 1 },
        { 'Rendering', nil, 'VorkuiBorder', 'OVERLAY' },
        --SPARK
        { 'Spark', 'Layer', 'OVERLAY' },
        { 'Spark', 'Size', 20, 20 },
        { 'Spark', 'BlendMode', 'ADD' },
        { 'CastSettings', 'AtlasName', 'Muzzle' },
        { 'CastSettings', 'Point', 'RIGHT', 'Castbar', 'RIGHT', 5, 0 },
        { 'ChannelSettings', 'AtlasName', 'Spark' },
        { 'ChannelSettings', 'Point', 'CENTER', 'Castbar', 'RIGHT', 0, 0 },
        --TAGS
        { 'Time', 'Layer', 'OVERLAY' },
        { 'Time', 'Font', 'DurationFont' },
        { 'Time', 'Point', 'RIGHT', 'Castbar' },

        { 'Text', 'Layer', 'OVERLAY' },
        { 'Text', 'Font', 'NormalFont' },
        { 'Text', 'Point', 'CENTER', 'Castbar' },

        --ICON
        { 'Icon', 'Size', 20, 20 },
        { 'Icon', 'Point', 'TOPLEFT', 'Castbar' },

        --SHIELD
        { 'Shield', 'Size', 20, 20 },
        { 'Shield', 'Point', 'LEFT', 'Text' },
        { 'Shield', 'Texture', 'GlobalIcon' },
        { 'Shield', 'TexCoord', 'DEFENSE' },

        --SAFEZONE
        { 'SafeZone', 'Layer', 'OVERLAY' },
        { 'SafeZone', 'BlendMode', 'ADD' },
        { 'SafeZone', 'VertexColor', { 255 / 255, 246 / 255, 0, 0.75 } },
    }

    if layout == 'Expanded' then
        data[#data + 1] = { nil, 'Size', 190, 20 }
    elseif layout == 'Minimalist' then
        data[#data + 1] = { nil, 'Size', 150, 20 }
    else
        print("|cFFFF1010 BAD PARTY LAYOUT |r")
    end

    registers(module, submodule, 'CastBar', data)

end

local function nameOption(layout, module, submodule)
    local data = {
        { nil, 'Enable', true },
        --TAGS
        { nil, 'Layer', 'OVERLAY' },
        { nil, 'Font', 'NameFont' },
        { nil, 'Tag', '[classification] [name] [difficulty][level]' },
    }

    if layout == 'Expanded' then
        data[#data + 1] = { nil, 'Point', 'TOPRIGHT', 'Frame', 'TOPRIGHT', -20, 0 }
    elseif layout == 'Minimalist' then
        data[#data + 1] = { nil, 'Point', 'TOPRIGHT', 'Frame', 'TOPRIGHT', -20, 0 }
    elseif layout == 'Compact' then
        data[#data + 1] = { nil, 'Point', 'LEFT', 'Frame', 'RIGHT', 20, 0 }
    else
        print ("|cFFFF1010 BAD PARTY LAYOUT |r")
    end

    registers(module, submodule, 'Name', data)
end

local function powerOption(layout, module, submodule)
    local enable = true

    if layout == 'Compact' then
        enable = false
    end

    local data = {
        { nil, 'Enable', enable },
        { nil, 'Point', 'TOPLEFT', 'Health', 'BOTTOMLEFT', -8, 0 },
        ----SLANT
        { 'SlantingSettings', 'Enable', true },
        { 'SlantingSettings', 'IgnoreBackground', true },
        { 'SlantingSettings', 'StaticLayer', 'BACKGROUND' },
        --RENDERING
        { 'Rendering', nil, 'VorkuiDefault', 'ARTWORK' },
        { 'Rendering', nil, 'VorkuiBorder', 'OVERLAY' },
        --TAGS
    }

    local size = #data

    if layout == 'Expanded' then
        data[size + 1] = { nil, 'Size', 117, 12 }
        data[size + 2] = { 'Value', 'Layer', 'OVERLAY' }
        data[size + 3] = { 'Value', 'Font', 'StackFont' }
        data[size + 4] = { 'Value', 'Point', 'BOTTOM', 'Frame' }
        data[size + 5] = { 'Value', 'Tag', '[powercolor][missingpp]' }
    elseif layout == 'Minimalist' then
        data[size + 1] = { nil, 'Size', 118, 8 }
    end

    registers(module, submodule, 'Power', data)

end

local function powerPredictionOption(layout, module, submodule)
    local enable = true

    if layout == 'Compact' then
        enable = false
    end

    local data = {
        { nil, 'Enable', enable },
        ----SLANT
        { 'SlantingSettings', 'Enable', true },
        { 'SlantingSettings', 'IgnoreBackground', true },
        { 'SlantingSettings', 'FillInverse', true },
        --RENDERING
        { 'Rendering', nil, 'VorkuiDefault', 'ARTWORK', 1 },
        { 'Rendering', nil, 'VorkuiBorder', 'OVERLAY' },
    }

    registers(module, submodule, 'PowerPrediction', data)

end

local function portraitOption(layout, module, submodule)
    local enable = true

    if layout ~= 'Expanded' then
        enable = false
    end

    local data = {
        { nil, 'Enable', enable },
        --TRANSFORM
        { nil, 'Size', 58, 58 },
        { nil, 'Point', 'TOPLEFT', 'Frame', 'TOPLEFT' },
        { nil, 'Type', '3D' },
        { nil, 'ModelDrawLayer', 'BACKGROUND' },

        { 'PostUpdate', 'Position', { 0.2, 0, 0 } },
        { 'PostUpdate', 'Rotation', -math.pi / 5 },
        { 'PostUpdate', 'CamDistance', 2 },
    }

    registers(module, submodule, 'Portrait', data)

end

local function buffOption(layout, module, submodule)

    local enable = true

    if layout ~= 'Expanded' then
        enable = false
    end

    local data = {
        { nil, 'Enable', enable },
        --TRANSFORM
        { nil, 'Size', 24*6 + 2*5, 24 },
        { nil, 'Point', 'BOTTOMLEFT', 'Frame', 'TOPLEFT', 0, 2 },
        { nil, 'ButtonSize', 24 },
        { nil, 'ButtonCount', 6 },
        { nil, 'ButtonSpacing', 2 },
        { nil, 'OnlyShowPlayer', true },
    }

    registers(module, submodule, 'Buffs', data)

end

local function debuffOption(layout, module, submodule)

    local enable = true

    if layout ~= 'Compact' then
        enable = false
    end

    local data = {
        { nil, 'Enable', enable },
        --TRANSFORM
        { nil, 'Size', 24*6 + 2*5, 24 },
        { nil, 'Point', 'TOPLEFT', 'Frame', 'BOTTOMLEFT', 0, 2 },
        { nil, 'ButtonSize', 24 },
        { nil, 'ButtonCount', 6 },
        { nil, 'ButtonSpacing', 2 },
    }

    registers(module, submodule, 'Debuffs', data)

end

local function indicatorOption(module, submodule, indicator, size, point, texture, texcoord, vertexcolor, gradientalpha, blendmode)
    local data = {
        { nil, 'Enable', enable },
        { nil, 'Size', unpack(size) },
        { nil, 'Point', unpack(point) },
        { nil, 'Texture', texture },
        { nil, 'TexCoord', texcoord },
        { nil, 'VertexColor', vertexcolor },
        { nil, 'GradientAlpha', gradientalpha },
        { nil, 'BlendMode', blendmode },
    }

    registers(module, submodule, indicator, data)
end

local function headerOption(module, submodule)
    Profiles:RegisterOption(module, submodule, nil, 'Header', 'Name', 'VorkuiParty')
    Profiles:RegisterOption(module, submodule, nil, 'Header', 'Template', nil)
    Profiles:RegisterOption(module, submodule, nil, 'Header', 'Visibility', 'custom [@raid6,exists] hide;show')
end

local function  attributesOption (layout, module, submodule)

    Profiles:RegisterOption(module, submodule, nil, nil, 'Layout', layout)

    if layout == 'Expanded' then
        Profiles:RegisterOption(module, submodule, nil, nil, 'Size', 195, 5*58+4*30)
        Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'point', 'TOP')
        Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'initial-width', 190)
        Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'initial-height', 58)
        Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'xOffset', 5)
        Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'yOffset', -30)
    elseif layout == 'Minimalist' then
        Profiles:RegisterOption(module, submodule, nil, nil, 'Size', 150, 5*44+4*25)
        Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'point', 'TOP')
        Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'initial-width', 150)
        Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'initial-height', 44)
        Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'xOffset', 1)
        Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'yOffset', -25)
    elseif layout == 'Compact' then
        Profiles:RegisterOption(module, submodule, nil, nil, 'Size', 156, 5*24+4*26)
        Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'point', 'TOP')
        Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'initial-width', 156)
        Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'initial-height', 24)
        Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'xOffset', 1)
        Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'yOffset', -26)
    else
        print ("|cFFFF1010 BAD PARTY LAYOUT |r")
    end
    Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'groupFilter', '1,2,3,4,5,6,7,8')
    Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'showRaid', false)
    Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'showParty', true)
    Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'showPlayer', true)
    Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'showSolo', false)
    Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'sortMethod', 'INDEX')
    Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'sortDir', 'ASC')
    Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'groupBy', 'GROUP')
    Profiles:RegisterOption(module, submodule, 'Attributes', nil, 'groupingOrder', '1,2,3,4,5,6,7,8')
end

--(module, submodule, object, component, type, optionName, defaultValue)
Themes["Default"].SetPartyProfile = function(layout)

    local module = 'UnitFrames'
    local submodule = 'PartyLayout'

    --Global OPTION
    Profiles:RegisterOption(module, submodule, nil, nil, 'Point', 'BOTTOM', 'UIParent', 'BOTTOM', 0, 10)

    headerOption(module, submodule)

    attributesOption(layout, module, submodule)

    --Unit OPTION
    healthOption(layout, module, submodule)
    healthPredictionOption(layout, module, submodule)
    absorbOption(layout, module, submodule)
    powerOption(layout, module, submodule)
    powerPredictionOption(layout, module, submodule)
    portraitOption(layout, module, submodule)

    indicatorOption(module, submodule, 'ClassIndicator',
            { 16, 16 },
            { 'TOPLEFT', 'Frame', 'TOPLEFT', -4, -2 },
            'ClassIcon',
            select(2, UnitClass("player")),
            nil,
            nil,
            nil
    )

    indicatorOption(module, submodule, 'RaidIndicator',
            { 16, 16 },
            { 'LEFT', 'Health', 'RIGHT', 0, 0 },
            'RaidIcon',
            nil,
            nil,
            nil,
            nil
    )

    indicatorOption(module, submodule, 'LeaderIndicator',
            { 64 / 4, 53 / 4 },
            { 'TOPRIGHT', 'Frame', 'TOPRIGHT' },
            'GlobalIcon',
            'LEADER',
            { 163 / 255, 220 / 255, 255 / 255 },
            nil,
            nil
    )

    indicatorOption(module, submodule, 'DeadOrGhostIndicator',
            { 20, 20 },
            { 'CENTER', 'Frame', 'CENTER' },
            'Status',
            'DIED',
            { 255 / 255, 68 / 255, 91 / 255 },
            nil,
            nil
    )

    indicatorOption(module, submodule, 'ResurrectIndicator',
            { 20, 20 },
            { 'CENTER', 'Frame', 'CENTER', 0, 0 },
            'Status',
            'RESURRECT',
            { 30 / 255, 223 / 255, 100 / 255 },
            nil,
            nil
    )

    indicatorOption(module, submodule, 'SummonIndicator',
            { 20, 20 },
            { 'CENTER', 'Health', 'CENTER' },
            'Phasing',
            'SUMMON',
            { 0 / 255, 204 / 255, 255 / 255 },
            nil,
            nil
    )

    indicatorOption(module, submodule, 'PhaseIndicator',
            { 20, 20 },
            { 'CENTER', 'Health', 'CENTER' },
            'Phasing',
            'PHASE',
            { 0 / 255, 204 / 255, 255 / 255 },
            nil,
            nil
    )

    nameOption(layout, module, submodule)
    castbarOption(layout, module, submodule)
    buffOption(layout, module, submodule)
    debuffOption(layout, module, submodule)

    --[[ TODO TEMPORARY FONT TO KEEP COMPATIBILTY WITH OLD EDITOR
    ["NameFont"] = {
				"Montserrat Medium", -- [1]
				20, -- [2]
				"OUTLINE", -- [3]
			},
    ["NormalFont"] = {
				"Montserrat Medium", -- [1]
				12, -- [2]
				"OUTLINE", -- [3]
			},
    ["StackFont"] = {
				"Montserrat Medium Italic", -- [1]
				16, -- [2]
				"OUTLINE", -- [3]
			},
	["DurationFont"] = {
				"Montserrat Medium", -- [1]
				12, -- [2]
				"OUTLINE", -- [3]
			},
	["BigValueFont"] = {
				"Montserrat Medium Italic", -- [1]
				18, -- [2]
				"OUTLINE", -- [3]
			},
	["ValueFont"] = {
				"Montserrat Medium Italic", -- [1]
				14, -- [2]
				"OUTLINE", -- [3]
			},

	["Submodules"] = {
				["Absorb"] = true,
				["Portrait"] = true,
				["Power"] = true,
				["LeaderIndicator"] = true,
				["Debuffs"] = true,
				["ResurrectIndicator"] = true,
				["SummonIndicator"] = true,
				["CastBar"] = true,
				["RestingIndicator"] = true,
				["CombatIndicator"] = true,
				["ClassIndicator"] = true,
				["DeadOrGhostIndicator"] = true,
				["Buffs"] = true,
				["FightIndicator"] = true,
				["RaidIndicator"] = true,
			},
    ]]--

    Profiles:RegisterOption(module, submodule, nil, nil, 'NameFont', 'Montserrat Medium', 20, 'OUTLINE')
    Profiles:RegisterOption(module, submodule, nil, nil, 'NormalFont', 'Montserrat Medium', 12, 'OUTLINE')
    Profiles:RegisterOption(module, submodule, nil, nil, 'StackFont', 'Montserrat Medium Italic', 16, 'OUTLINE')
    Profiles:RegisterOption(module, submodule, nil, nil, 'DurationFont', 'Montserrat Medium', 12, 'OUTLINE')
    Profiles:RegisterOption(module, submodule, nil, nil, 'BigValueFont', 'Montserrat Medium Italic', 18, 'OUTLINE')
    Profiles:RegisterOption(module, submodule, nil, nil, 'ValueFont', 'Montserrat Medium Italic', 14, 'OUTLINE')

end