---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by flori.
--- DateTime: 12/11/2020 21:40
---
local _, Plugin = ...

local LibGUI = Plugin.LibGUI

local function CreateExitButton(self)
    local exitButton = CreateFrame("Button", self.data.name.."ExitButton", self.frame, "UIButtonTemplate")
    exitButton:SetSize(32,32)
    exitButton:SetPoint("TOPRIGHT")

    self.frame.exitButton = exitButton
end


--CreateFrame(frameType [, name, parent, template, id])
local function initWidget(self, parent)

    local frameData = self.data or {}
    local frame = CreateFrame("Frame", frameData.name, parent, frameData.template)

    if frameData.size then
        frame:SetSize(unpack(frameData.size))
    end

    if frameData.point then
        frame:SetPoint(unpack(frameData.point))
    end

    local background = frame:CreateTexture()
    background:SetAllPoints()
    background:SetColorTexture(0,0,0,1)

    frame.background = background

    CreateExitButton(self)
    self.frame = frame

end

LibGUI.CreateWidget['frame'] = function(widget, parent)

    if not parent then
        initWidget(widget, UIParent)
    else
        initWidget(widget, parent.frame)
    end
end
