---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by flori.
--- DateTime: 19/10/2020 23:53
---

local V, C, L = select(2, ...):unpack()

local UnitFrames = V["UnitFrames"]
local Class = select(2, UnitClass("player"))

function UnitFrames:Player()

    self:RegisterForClicks("AnyUp")
    self:SetScript("OnEnter", UnitFrame_OnEnter)
    self:SetScript("OnLeave", UnitFrame_OnLeave)

    local Health = self:CreateTexture(nil, "ARTWORK")
    Health:SetSize(256,32)
    Health:SetPoint("TOPLEFT", self, "TOPLEFT")
    Health:SetTexture([[Interface\AddOns\VorkUI\Medias\slantedTest.tga]])

    Health.background = self:CreateTexture(nil, "BACKGROUND")
    Health.background:SetSize(256,32)
    Health.background:SetAllPoints(Health)
    Health.background:SetTexture([[Interface\AddOns\VorkUI\Medias\slantedTest.tga]])
    Health.background:SetColorTexture(0,0,0,1)

    Health.colorDisconnected = true
    Health.colorClass = true
    Health.colorReaction = true

    self:HookScript("OnEnter", UnitFrames.MouseOnPlayer)
    self:HookScript("OnLeave", UnitFrames.MouseOnPlayer)

    -- Register with oUF
    self.SlantHealth = Health
    self.SlantHealth.bg = Health.background

end
