---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by flori.
--- DateTime: 20/10/2020 00:11
---

local V,C,L = select(2,...):unpack()

local CreateFrame = CreateFrame

local Load = CreateFrame("Frame")

function Load:OnEvent(event)
    if (event == "PLAYER_LOGIN") then
        V["Medias"]:Enable()
        V["UnitFrames"]:Enable()
        --Now that all systems and medias are loaded, we can generate config frame
        if not V["Profiles"]:IsReady() then
            V["Themes"]:RegisterTheme("Default")
            V["Install"]:Launch(VorkuiDB)
        else
            V["Install"]:GenerateConfigFrame()
        end
    end
end

Load:RegisterEvent("PLAYER_LOGIN")
Load:SetScript("OnEvent", Load.OnEvent)

V["Loading"] = Load
