---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by flori.
--- DateTime: 20/10/2020 00:11
---

local V, C, L = select(2,...):unpack()

local CreateFrame = CreateFrame
local _G = _G

local Load = CreateFrame("Frame")

local function moveBlizzardFrame()

    local belowMinimapContainer = _G.UIWidgetBelowMinimapContainerFrame
    belowMinimapContainer:ClearAllPoints()
    belowMinimapContainer:SetPoint("TOP", 0, -50)

end

function Load:OnEvent(event, ...)
    if (event == "PLAYER_LOGIN") then
        moveBlizzardFrame()
        V["Utils"]:Enable()
        V["Medias"]:Enable()
        --Now that all systems and medias are loaded, we can generate config frame
        if not V["Profiles"]:IsReady() then
            --print ("REGISTER DATA")
            --V["Themes"]:RegisterTheme("Default")
            --print ("LAUNCH INSTALLER")
            --V["Install"]:Launch(VorkuiDB)
        else
            --print ("GENERATE CONFIG FRAME")
            V["Install"]:GenerateConfigFrame()
            V["Editor"]:CreateGUI()
        end
        V["UnitFrames"]:Enable()
    elseif (event == 'ADDON_LOADED') then
        if IsAddOnLoaded("Blizzard_DebugTools") then
            _G.TableAttributeDisplay:SetSize(800, 600)
            _G.TableAttributeDisplay.LinesScrollFrame:SetSize(740, 500)
        end
    end
end

Load:RegisterEvent("PLAYER_LOGIN")
Load:RegisterEvent("ADDON_LOADED")
Load:SetScript("OnEvent", Load.OnEvent)

V["Loading"] = Load
