---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by flori.
--- DateTime: 01/11/2020 22:11
---

local V,C,L = select(2,...):unpack()

local VorkuiMedia = CreateFrame("Frame")

V["Medias"] = VorkuiMedia