---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by flori.
--- DateTime: 01/11/2020 22:11
---

local V,C,L = select(2,...):unpack()

local LibAtlas = LibStub:GetLibrary("LibAtlas")
local LibSharedMedia = LibStub:GetLibrary("LibSharedMedia-3.0")

local Medias = CreateFrame("Frame")

local Fonts = {}
local StatusBar = {}

function Medias:GetLSM()
    return LibSharedMedia
end

function Medias:PushFontObject(name, adress, size, ...)
    if type(size) == 'table' then
        for _, s in ipairs(size) do
            Fonts[name..s] = CreateFont("Vorkaui" .. name .. s)
            Fonts[name..s]:SetFont(LibSharedMedia:Fetch('font', adress), s, ...)
        end
    else
        Fonts[name] = CreateFont("Vorkaui"..name)
        Fonts[name]:SetFont(LibSharedMedia:Fetch('font', adress), size, ...)
    end
end

function Medias:GetFont(name)
    if Fonts[name] then
        return Fonts[name]
    end

    --return first iteration find, order not assured
    for k, v in pairs(Fonts) do
        if k:find(name) ~= nil then
            return v
        end
    end

    return LibSharedMedia:Fetch('font', name)
end

function Medias:LoadFont(name, adress, size, ...)

    LibSharedMedia:Register('font', name, self.MediaPath["Fonts"] .. adress)
    self:PushFontObject(name, adress, size, ...)

end

function Medias:GetLibAtlas()
    return LibAtlas
end

function Medias:LoadAtlas(name, adress, settings)
    LibAtlas:RegisterAtlas(name, self.MediaPath["Icons"]..adress, settings)
end

function Medias:GetStatusBar(name)
    return StatusBar[name] or LibSharedMedia:Fetch('statusbar', name)
end

function Medias:LoadStatusBar(name, adress)
    LibSharedMedia:Register('statusbar', name, self.MediaPath["Textures"]..adress)
    StatusBar[name] = self.MediaPath["Textures"]..adress
end

V["Medias"] = Medias