---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by f.guilleminot.
--- DateTime: 31/12/2020 10:01
---
local V  = select(2, ...):unpack()

local Themes = CreateFrame("Frame")

local themes = {}

function Themes:RegisterTheme(name, partyLayout, raidLayout)
    if themes[name] then
        return
    end

    if not Themes[name] then
        print ("|cFFFF2200 ERROR REGISTER THEME FUNCTION MISSING |r")
        return
    end

    if not Themes[name].RegisterModules then
        print ("|cFFFF2200 ERROR REGISTER MODULE THEME FUNCTION MISSING |r")
        return
    end

    themes[name] = Themes[name].RegisterModules(partyLayout, raidLayout)
end

function Themes:ApplyTheme(name)
    if not themes[name] then
        print ("|cFFFF2200 ERROR THEME MISSING|r:", name)
        return
    end

    print ("|cFF10FF10 APPLY THEME|r:", name)
end

V.Themes = Themes