---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by flori.
--- DateTime: 11/11/2020 09:39
---
local AddOn = ...
local V = select(2, ...):unpack()

local AceGUI = LibStub("AceGUI-3.0")
local Install = CreateFrame("Frame")

--TODO TABLE OF INSTALL FRAME
local function GenerateInstallFrame(self, db)

    --local frame = AceGUI:Create("Frame")
    --frame:SetTitle("Example Frame")
    --frame:SetStatusText("AceGUI-3.0 Example Container Frame")
    --frame:SetCallback("OnClose", function(widget) AceGUI:Release(widget) end)
    --frame:SetLayout("Flow")
    --
    --local editbox = AceGUI:Create("EditBox")
    --editbox:SetLabel("Insert text:")
    --editbox:SetWidth(200)
    --frame:AddChild(editbox)
    --
    --local button = AceGUI:Create("Button")
    --button:SetText("Click Me!")
    --button:SetWidth(200)
    --frame:AddChild(button)

    db.Profile = {
        Theme = "Default",
        PartyLayout = "Compact",
        RaidLayout = "Minimalist"
    }

    Install.Frame = frame

end

function Install:Launch(db)
    GenerateInstallFrame(self, db)
end

V.Install = Install