---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by flori.
--- DateTime: 01/11/2020 21:54
---

local V, C, L = select(2, ...):unpack()
local Medias = V["Medias"]

Medias.MediaPath = {
    Fonts = [[Interface\AddOns\VorkUI\Medias\Fonts\]],
    Textures = [[Interface\AddOns\VorkUI\Medias\Textures\]],
    Icons = [[Interface\AddOns\VorkUI\Medias\Icons\]],
}

local StatusBarAdress = {
    {[[StatusBar\bubbles.tga]], 'VorkuiBubbles'},
    {[[StatusBar\default.tga]], 'VorkuiDefault'},
    {[[StatusBar\background.tga]], 'VorkuiBackground'},
    {[[StatusBar\border.tga]], 'VorkuiBorder'},
}
local FontAdress = {
    {'Montserrat-Black.ttf', 'Montserrat Black'},
    {'Montserrat-BlackItalic.ttf', 'Montserrat Black Italic'},
    {'Montserrat-Bold.ttf', 'Montserrat Bold'},
    {'Montserrat-BoldItalic.ttf', 'Montserrat Bold Italic'},
    {'Montserrat-ExtraBold.ttf', 'Montserrat Extra Bold'},
    {'Montserrat-ExtraBoldItalic.ttf', 'Montserrat Extra Bold Italic'},
    {'Montserrat-ExtraLight.ttf', 'Montserrat Extra Light'},
    {'Montserrat-ExtraLightItalic.ttf', 'Montserrat Extra Light Italic'},
    {'Montserrat-Italic.ttf', 'Montserrat Italic'},
    {'Montserrat-Light.ttf', 'Montserrat Light'},
    {'Montserrat-LightItalic.ttf', 'Montserrat Light Italic'},
    {'Montserrat-Medium.ttf', 'Montserrat Medium'},
    {'Montserrat-MediumItalic.ttf', 'Montserrat Medium Italic'},
    {'Montserrat-Regular.ttf', 'Montserrat'},
    {'Montserrat-SemiBold.ttf', 'Montserrat SemiBold'},
    {'Montserrat-SemiBoldItalic.ttf', 'Montserrat SemiBold Italic'},
    {'Montserrat-Thin.ttf', 'Montserrat Thin'},
    {'Montserrat-ThinItalic.ttf', 'Montserrat Thin Italic'},
}
local FontSettings = {
    ["Montserrat Black"] = {
        {},
        "OUTLINE"
    },
    ["Montserrat Black Italic"] = {
        {},
        "OUTLINE"
    },
    ["Montserrat Bold"] = {
        { 16 },
        "OUTLINE"
    },
    ["Montserrat Bold Italic"] = {
        {},
        "OUTLINE"
    },
    ["Montserrat Extra Bold"] = {
        {  },
        "OUTLINE"
    },
    ["Montserrat Extra Bold Italic"] = {
        {},
        "OUTLINE"
    },
    ["Montserrat Extra Light"] = {
        { },
        "OUTLINE"
    },
    ["Montserrat Extra Light Italic"] = {
        {},
        "OUTLINE"
    },
    ["Montserrat Italic"] = {
        { 10, 14, 22, 30},
        "OUTLINE"
    },
    ["Montserrat Light"] = {
        {},
        "OUTLINE"
    },
    ["Montserrat Light Italic"] = {
        {},
        "OUTLINE"
    },
    ["Montserrat Medium"] = {
        { 10, 12, 14, 20 },
        "OUTLINE"
    },
    ["Montserrat Medium Italic"] = {
        { 10, 14, 16, 18, 22 },
        "OUTLINE"
    },
    ["Montserrat"] = {
        { 10, 14, 22 },
        "OUTLINE"
    },
    ["Montserrat SemiBold"] = {
        { 16, 22 },
        "OUTLINE"
    },
    ["Montserrat SemiBold Italic"] = {
        { 10, 22, 26 },
        "OUTLINE"
    },
    ["Montserrat Thin"] = {
        {},
        "OUTLINE"
    },
    ["Montserrat Thin Italic"] = {
        {},
        "OUTLINE"
    },
}
local AtlasAdress = {
    { [[Atlas\class.tga]], 'ClassIcon' },
    { [[Atlas\general.tga]], 'GlobalIcon' },
    { [[Atlas\raid_icons.tga]], 'RaidIcon' },
    { [[Atlas\muzzle.tga]], 'Muzzle' },
    { [[Atlas\flame.tga]], 'Flame' },
    { [[Atlas\spark.tga]], 'Spark' },
    { [[Atlas\dirt.tga]], 'Dirt' },
    { [[Atlas\status.tga]], 'Status' },
    { [[Atlas\phasing.tga]], 'Phasing' },
}
local AtlasSettings = {
    ["ClassIcon"] = {
        width = 512,
        height = 256,
        ["DEMONHUNTER"] = {0, 80, 0, 82},
        ["DEATHKNIGHT"] = {80, 158, 0, 82},
        ["DRUID"] = {158, 239, 0, 70},
        ["HUNTER"] = {239, 317, 0, 82},
        ["MAGE"] = {317, 397, 0, 80},
        ["WARLOCK"] = {397, 480, 0, 83},
        ["MONK"] = {0, 80, 83, 163},
        ["PALADIN"] = {80, 155, 83, 165},
        ["PRIEST"] = {155, 237, 83, 153},
        ["ROGUE"] = {237, 320, 83, 164},
        ["SHAMAN"] = {320, 402, 83, 163},
        ["WARRIOR"] = {402, 472, 83, 165},
        ["BLANK"] = {0, 80, 176, 256}
    },
    ["GlobalIcon"] = {
        width = 512,
        height = 128,
        ["AGILITY"] = {0, 63, 0, 64},
        ["INTELLIGENCE"] = {63, 107, 0, 64},
        ["LEADER"] = {107, 171, 0, 53},
        ["STAMINA"] = {171, 235, 0, 64},
        ["HEALTH"] = {235, 299, 0, 57},
        ["MANA"] = {299, 362, 0, 64},
        ["MAELSTROM"] = {362, 401, 0, 64},
        ["ENERGY"] = {401, 465, 0, 36},
        ["RUNICPOWER"] = {0, 55, 64, 128},
        ["RAGE"] = {55, 119, 64, 128},
        ["VERSATILITY"] = {119, 183, 64, 120},
        ["CRITICAL"] = {183, 247, 64, 128},
        ["HASTE"] = {247, 311, 64, 128},
        ["RESTING"] = {311, 375, 64, 124},
        ["DEFENSE"] = {375, 429, 64, 126},
        ["MASTERY"] = {429, 493, 46, 88},
        ["STRENGTH"] = {429, 493, 92, 126},
        ["FOCUS"] = {401, 465, 0, 36}, --same as energy
        ["FURY"] = {55, 119, 64, 128}, --same as rage
    },
    ["RaidIcon"] = {
        width = 256,
        height = 256,
        ["STAR"] = {0, 64, 0, 64},
        ["CIRCLE"] = {64, 128, 0, 64},
        ["DIAMOND"] = {128, 192, 0, 64},
        ["TRIANGLE"] = {192, 256, 0, 64},
        ["MOON"] = {0, 64, 64, 128},
        ["SQUARE"] = {64, 128, 64, 128},
        ["CROSS"] = {128, 192, 64, 128},
        ["SKULL"] = {192, 256, 64, 128},
    },
    ["Muzzle"] = {
        width = 256,
        height = 128,
        [1] = {0, 64, 0, 64},
        [2] = {64, 128, 0, 64},
        [3] = {128, 192, 0, 64},
        [4] = {192, 256, 0, 64},
        [5] = {0, 64, 64, 128},
    },
    ["Flame"] = {
        width = 128,
        height = 128,
        [1] = {0, 64, 0, 64},
        [2] = {64, 128, 0, 64},
        [3] = {0, 64, 64, 128},
        [4] = {64, 128, 64, 128},
    },
    ["Spark"] = {
        width = 128,
        height = 128,
        [1] = {0, 64, 0, 64},
        [2] = {64, 128, 0, 64},
        [3] = {0, 64, 64, 128},
        [4] = {64, 128, 64, 128},
    },
    ["Dirt"] = {
        width = 128,
        height = 128,
        [1] = {0, 64, 0, 64},
        [2] = {64, 128, 0, 64},
        [3] = {0, 64, 64, 128},
        [4] = {64, 128, 64, 128},
    },
    ["Status"] = {
        width = 128,
        height = 64,
        ["DIED"] = {0, 64, 0, 64},
        ["RESURRECT"] = {64, 128, 0, 64},
    },
    ["Phasing"] = {
        width = 128,
        height = 64,
        ["PHASE"] = {0, 64, 0, 64},
        ["SUMMON"] = {64, 128, 0, 64},
    },
}

local ParticlesAdress = {
    { [[Particles\muzzle_01.tga]], 'Spark' },
    { [[Particles\muzzle_02.tga]], 'Spark2' },
    { [[Particles\scorch_03.tga]], 'Scorch' },
}

function Medias:GetFontAddress(name, fullpath)

    for _, v in ipairs(FontAdress) do
        if v[2] == name then
            if fullpath then
                return Medias.MediaPath.Fonts .. v[1]
            else
                return v[1]
            end
        end
    end

    return nil
end

function Medias:LoadAllFonts()

    for _, v in ipairs(FontAdress) do
        if FontSettings[ v[2] ] ~= nil then
            Medias:LoadFont(v[2], v[1],unpack(FontSettings[ v[2] ]))
        end
    end

end

function Medias:LoadAllAtlas()
    for _, v in pairs( AtlasAdress ) do
        Medias:LoadAtlas(v[2], v[1],  AtlasSettings[ v[2] ])
    end
end

function Medias:LoadAllTextures()
    for _, v in pairs( StatusBarAdress ) do
        Medias:LoadStatusBar(v[2], v[1])
    end
end

function Medias:LoadParticles()
    for _, v in pairs( ParticlesAdress ) do
        Medias:LoadParticle(v[2], v[1])
    end
end

function Medias:Enable()
    self:LoadAllFonts()
    self:ChangeSystemFonts()
    self:LoadAllAtlas()
    self:LoadAllTextures()
    self:LoadParticles()
end